### ISSUE TITLE
Setup Cellery on existing cluster fails when gcp cluster is used

### ISSUE THREAD

**Issue by MadhukaHarith92** [wso2-cellery/sdk#373]
**Description:**
When creating cellery runtime on existing gcp cluster (volatile) CLI outputs following error message.

✔  cellery setup
✔ Create
✔ Existing cluster
✔ Non persistent volume
✔ Basic
✔ Load balancer [gcp, docker for desktop]
⠙ Creating cellery runtimepanic: runtime error: index out of range

goroutine 1 [running]:
github.com/cellery-io/sdk/components/cli/pkg/kubectl.GetMasterNodeName(0xc00068d6b0, 0x480c9ee, 0xc0005ca340, 0x3b)
/build/jenkins-home/goProjects/src/github.com/cellery-io/sdk/components/cli/pkg/kubectl/get.go:57 +0x1be
github.com/cellery-io/sdk/components/cli/pkg/runtime.labelMasterNode(0x4aa68d5, 0x1f)
/build/jenkins-home/goProjects/src/github.com/cellery-io/sdk/components/cli/pkg/runtime/runtime.go:200 +0x26
github.com/cellery-io/sdk/components/cli/pkg/runtime.CreateRuntime(0xc00002c2a0, 0x22, 0xc001000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/build/jenkins-home/goProjects/src/github.com/cellery-io/sdk/components/cli/pkg/runtime/runtime.go:71 +0x186
github.com/cellery-io/sdk/components/cli/pkg/commands.RunSetupCreateOnExistingCluster(0xc001000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)

**Affected Product Version:**
0.2.1

**OS, DB, other environment details and versions:**    
Existing cluster running on GCP

**Steps to reproduce:**
1. Create a gcp cluster manually.
2. Point to the created cluster. 
3. Create a cellery runtime by executing following command.
`cellery setup create existing --complete --loadbalancer`

**Comment by MadhukaHarith92** [comment]
Note: After creating gcp cluster grant cluster-admin permissions to the current user by executing following command
`kubectl create clusterrolebinding cluster-admin-binding \
--clusterrole=cluster-admin \
--user=$(gcloud config get-value core/account)
}`
