### ISSUE TITLE
Error when invoking the HR API with composites

### ISSUE THREAD

**Issue by sinthuja** [wso2-cellery/sdk#636]
**Description:**
- Deployed HR sample as composite
- Manually created an API for HR service
- Invoked the service and noticed the below error.

```
[DEBUG] 2019-09-05 11:09:52.132 [grpc-default-executor-2] [composite] [193f13ad935561c063eb704eea780d30] CelleryCellInterceptorService - Destination cannot be found in request attributes.
[DEBUG] 2019-09-05 11:09:52.135 [grpc-default-executor-2] [composite] [193f13ad935561c063eb704eea780d30] CelleryCellInterceptorService - Request from Istio-Proxy (destination:hr-comp-1-0-0-4f0119f0--hr-service.default):
attributes {
  source {
    address {
      socket_address {
        address: "10.244.0.47"
        port_value: 57702
      }
    }
  }
  destination {
    address {
      socket_address {
        address: "10.244.0.46"
        port_value: 8080
      }
    }
  }
  request {
    http {
      id: "4291062533923248573"
      method: "GET"
      headers {
        key: "x-b3-globalgatewaycorrelationid"
        value: "d740c073-df33-4103-b658-250553955d49"
      }
      headers {
        key: "cellery-authorization"
        value: "Bearer eyJ4NXQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJraWQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhbGljZSIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL3JvbGUiOiJJbnRlcm5hbFwvZXZlcnlvbmUsYWRtaW4iLCJzY29wZSI6WyJkZWZhdWx0Il0sImlzcyI6Imh0dHBzOlwvXC9zdHMuY2VsbGVyeS5pbyIsImtleXR5cGUiOiJQUk9EVUNUSU9OIiwiY29uc3VtZXJLZXkiOiJpeVF1M0tyRmVaWE9WZFlPQWtmdWsxRE9MYUVhIiwiZXhwIjoxNTY3NjgyNTYyLCJpYXQiOjE1Njc2ODEzNjIsImp0aSI6IjNkYmJiMDUyLWI3YTUtNDFlMS05MDdiLWNlNWU0ZWRlOGNmMSJ9.Wy-tQbCZ9tmQXvkdeY_7sAtwSe6o2MlWUPAeERElEImIKyH35IZzNYM30dUrweujrOvA3PdVdbHzkeVCOMcAvBaWpVJX8jIsserXO8OQ8REETcL91ejPz-ECrzZeEvZvHuo7CzGgwHFEvY4wXIJW6CGF2F1QT3QXa0gbYESLqCDDnKydclHvC3Z362hy6T30Bvzahl0IYWAcnz9xReYVmpGgH2LwuvCPCQxNfSw6znq2X2ZsuxXra8un9eJ8iaFOMK2YqEdKPcIXVKtEjMLolaJw4vBNApu1oLk5JVSwSYcKn__5Eegqv9BUTQhDaRSrnfEY3kC0YJGZbgwVQ4whrw"
      }
      headers {
        key: ":authority"
        value: "hr-comp-1-0-0-4f0119f0--hr-service.default"
      }
      headers {
        key: "x-b3-sampled"
        value: "1"
      }
      headers {
        key: "x-scheme"
        value: "https"
      }
      headers {
        key: "x-real-ip"
        value: "10.244.0.1"
      }
      headers {
        key: "x-original-uri"
        value: "/hr-com/1.0.0/hr"
      }
      headers {
        key: "x-b3-parentspanid"
        value: "544d85afddcb3b56"
      }
      headers {
        key: "x-request-id"
        value: "193f13ad935561c063eb704eea780d30"
      }
      headers {
        key: "x-forwarded-for"
        value: "10.244.0.1"
      }
      headers {
        key: "accept"
        value: "*/*"
      }
      headers {
        key: "user-agent"
        value: "Synapse-PT-HttpComponents-NIO"
      }
      headers {
        key: "x-b3-traceid"
        value: "544d85afddcb3b56"
      }
      headers {
        key: "x-envoy-internal"
        value: "true"
      }
      headers {
        key: "authorization"
        value: "Bearer 37ecac63-6f43-386d-b9d9-e6364b7fc180"
      }
      headers {
        key: ":method"
        value: "GET"
      }
      headers {
        key: "x-forwarded-host"
        value: "wso2-apim-gateway"
      }
      headers {
        key: ":path"
        value: "/hr"
      }
      headers {
        key: "x-forwarded-proto"
        value: "https"
      }
      headers {
        key: "x-forwarded-port"
        value: "443"
      }
      headers {
        key: "x-b3-spanid"
        value: "63686b2b624466a4"
      }
      path: "/hr"
      host: "hr-comp-1-0-0-4f0119f0--hr-service.default"
      protocol: "HTTP/1.1"
    }
  }
}

[DEBUG] 2019-09-05 11:09:52.136 [grpc-default-executor-2] [composite] [193f13ad935561c063eb704eea780d30] CelleryCellInterceptorService - Destination cannot be found in request attributes.
[DEBUG] 2019-09-05 11:09:52.136 [grpc-default-executor-2] [composite] [193f13ad935561c063eb704eea780d30] CelleryCellInterceptorService - Request Attributes:
{}
[DEBUG] 2019-09-05 11:09:52.137 [grpc-default-executor-2] [composite] [193f13ad935561c063eb704eea780d30] CelleryCellInboundInterceptorService - Intercepted Sidecar Inbound Request:
Source:{}
Destination:{
  "Cell Name": "hr-comp-1-0-0-4f0119f0",
  "Workload": "hr-comp-1-0-0-4f0119f0--hr-service.default"
}

[INFO ] 2019-09-05 11:09:52.137 [grpc-default-executor-2] [composite] [193f13ad935561c063eb704eea780d30] CelleryCellSTSServer - Validating isAuthenticaitonRequered for context: /hr
[INFO ] 2019-09-05 11:09:52.137 [grpc-default-executor-2] [composite] [193f13ad935561c063eb704eea780d30] CelleryCellSTSServer - []
[DEBUG] 2019-09-05 11:09:52.137 [grpc-default-executor-2] [composite] [193f13ad935561c063eb704eea780d30] CelleryCellStsService - Authentication is required for the request ID: 193f13ad935561c063eb704eea780d30
[DEBUG] 2019-09-05 11:09:52.137 [grpc-default-executor-2] [composite] [193f13ad935561c063eb704eea780d30] CelleryCellStsService - Caller cell : null
[DEBUG] 2019-09-05 11:09:52.137 [grpc-default-executor-2] [composite] [193f13ad935561c063eb704eea780d30] CelleryCellStsService - Incoming JWT : eyJ4NXQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJraWQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhbGljZSIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL3JvbGUiOiJJbnRlcm5hbFwvZXZlcnlvbmUsYWRtaW4iLCJzY29wZSI6WyJkZWZhdWx0Il0sImlzcyI6Imh0dHBzOlwvXC9zdHMuY2VsbGVyeS5pbyIsImtleXR5cGUiOiJQUk9EVUNUSU9OIiwiY29uc3VtZXJLZXkiOiJpeVF1M0tyRmVaWE9WZFlPQWtmdWsxRE9MYUVhIiwiZXhwIjoxNTY3NjgyNTYyLCJpYXQiOjE1Njc2ODEzNjIsImp0aSI6IjNkYmJiMDUyLWI3YTUtNDFlMS05MDdiLWNlNWU0ZWRlOGNmMSJ9.Wy-tQbCZ9tmQXvkdeY_7sAtwSe6o2MlWUPAeERElEImIKyH35IZzNYM30dUrweujrOvA3PdVdbHzkeVCOMcAvBaWpVJX8jIsserXO8OQ8REETcL91ejPz-ECrzZeEvZvHuo7CzGgwHFEvY4wXIJW6CGF2F1QT3QXa0gbYESLqCDDnKydclHvC3Z362hy6T30Bvzahl0IYWAcnz9xReYVmpGgH2LwuvCPCQxNfSw6znq2X2ZsuxXra8un9eJ8iaFOMK2YqEdKPcIXVKtEjMLolaJw4vBNApu1oLk5JVSwSYcKn__5Eegqv9BUTQhDaRSrnfEY3kC0YJGZbgwVQ4whrw
[DEBUG] 2019-09-05 11:09:52.138 [grpc-default-executor-2] [composite] [193f13ad935561c063eb704eea780d30] CelleryCellStsService - Incoming request to composite STS from {}
[DEBUG] 2019-09-05 11:09:52.138 [grpc-default-executor-2] [composite] [193f13ad935561c063eb704eea780d30] CelleryCellStsService - Validating incoming JWT eyJ4NXQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJraWQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhbGljZSIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL3JvbGUiOiJJbnRlcm5hbFwvZXZlcnlvbmUsYWRtaW4iLCJzY29wZSI6WyJkZWZhdWx0Il0sImlzcyI6Imh0dHBzOlwvXC9zdHMuY2VsbGVyeS5pbyIsImtleXR5cGUiOiJQUk9EVUNUSU9OIiwiY29uc3VtZXJLZXkiOiJpeVF1M0tyRmVaWE9WZFlPQWtmdWsxRE9MYUVhIiwiZXhwIjoxNTY3NjgyNTYyLCJpYXQiOjE1Njc2ODEzNjIsImp0aSI6IjNkYmJiMDUyLWI3YTUtNDFlMS05MDdiLWNlNWU0ZWRlOGNmMSJ9.Wy-tQbCZ9tmQXvkdeY_7sAtwSe6o2MlWUPAeERElEImIKyH35IZzNYM30dUrweujrOvA3PdVdbHzkeVCOMcAvBaWpVJX8jIsserXO8OQ8REETcL91ejPz-ECrzZeEvZvHuo7CzGgwHFEvY4wXIJW6CGF2F1QT3QXa0gbYESLqCDDnKydclHvC3Z362hy6T30Bvzahl0IYWAcnz9xReYVmpGgH2LwuvCPCQxNfSw6znq2X2ZsuxXra8un9eJ8iaFOMK2YqEdKPcIXVKtEjMLolaJw4vBNApu1oLk5JVSwSYcKn__5Eegqv9BUTQhDaRSrnfEY3kC0YJGZbgwVQ4whrw
[DEBUG] 2019-09-05 11:09:52.138 [grpc-default-executor-2] [composite] [193f13ad935561c063eb704eea780d30] SelfContainedTokenValidator - Validating token: eyJ4NXQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJraWQiOiJOVEF4Wm1NeE5ETXlaRGczTVRVMVpHTTBNekV6T0RKaFpXSTRORE5sWkRVMU9HRmtOakZpTVEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhbGljZSIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL3JvbGUiOiJJbnRlcm5hbFwvZXZlcnlvbmUsYWRtaW4iLCJzY29wZSI6WyJkZWZhdWx0Il0sImlzcyI6Imh0dHBzOlwvXC9zdHMuY2VsbGVyeS5pbyIsImtleXR5cGUiOiJQUk9EVUNUSU9OIiwiY29uc3VtZXJLZXkiOiJpeVF1M0tyRmVaWE9WZFlPQWtmdWsxRE9MYUVhIiwiZXhwIjoxNTY3NjgyNTYyLCJpYXQiOjE1Njc2ODEzNjIsImp0aSI6IjNkYmJiMDUyLWI3YTUtNDFlMS05MDdiLWNlNWU0ZWRlOGNmMSJ9.Wy-tQbCZ9tmQXvkdeY_7sAtwSe6o2MlWUPAeERElEImIKyH35IZzNYM30dUrweujrOvA3PdVdbHzkeVCOMcAvBaWpVJX8jIsserXO8OQ8REETcL91ejPz-ECrzZeEvZvHuo7CzGgwHFEvY4wXIJW6CGF2F1QT3QXa0gbYESLqCDDnKydclHvC3Z362hy6T30Bvzahl0IYWAcnz9xReYVmpGgH2LwuvCPCQxNfSw6znq2X2ZsuxXra8un9eJ8iaFOMK2YqEdKPcIXVKtEjMLolaJw4vBNApu1oLk5JVSwSYcKn__5Eegqv9BUTQhDaRSrnfEY3kC0YJGZbgwVQ4whrw
[DEBUG] 2019-09-05 11:09:52.139 [grpc-default-executor-2] [composite] [193f13ad935561c063eb704eea780d30] SelfContainedTokenValidator - Issuer validated successfully. Issuer : https://sts.cellery.io
[DEBUG] 2019-09-05 11:09:52.139 [grpc-default-executor-2] [composite] [193f13ad935561c063eb704eea780d30] CelleryCellInterceptorService - Destination cannot be found in request attributes.
[ERROR] 2019-09-05 11:09:52.139 [grpc-default-executor-2] [composite] [193f13ad935561c063eb704eea780d30] CelleryCellInterceptorService - Error while handling request from istio-proxy to (destination:hr-comp-1-0-0-4f0119f0--hr-service.default)
io.cellery.security.cell.sts.server.core.service.CelleryCellSTSException: Error while validating JWT token
	at io.cellery.security.cell.sts.server.core.service.CelleryCellStsService.handleRequestComposite(CelleryCellStsService.java:151) ~[io.cellery.security.cell.sts.server-0.3.1-SNAPSHOT.jar:0.3.1-SNAPSHOT]
	at io.cellery.security.cell.sts.server.core.service.CelleryCellStsService.handleInboundRequest(CelleryCellStsService.java:114) ~[io.cellery.security.cell.sts.server-0.3.1-SNAPSHOT.jar:0.3.1-SNAPSHOT]
	at io.cellery.security.cell.sts.server.core.service.CelleryCellInboundInterceptorService.handleRequest(CelleryCellInboundInterceptorService.java:44) ~[io.cellery.security.cell.sts.server-0.3.1-SNAPSHOT.jar:0.3.1-SNAPSHOT]
	at io.cellery.security.cell.sts.server.core.service.CelleryCellInterceptorService.check(CelleryCellInterceptorService.java:106) [io.cellery.security.cell.sts.server-0.3.1-SNAPSHOT.jar:0.3.1-SNAPSHOT]
	at io.envoyproxy.envoy.service.auth.v2.AuthorizationGrpc$MethodHandlers.invoke(AuthorizationGrpc.java:246) [io.cellery.security.cell.sts.server-0.3.1-SNAPSHOT.jar:0.3.1-SNAPSHOT]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171) [io.cellery.security.cell.sts.server-0.3.1-SNAPSHOT.jar:0.3.1-SNAPSHOT]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283) [io.cellery.security.cell.sts.server-0.3.1-SNAPSHOT.jar:0.3.1-SNAPSHOT]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:707) [io.cellery.security.cell.sts.server-0.3.1-SNAPSHOT.jar:0.3.1-SNAPSHOT]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [io.cellery.security.cell.sts.server-0.3.1-SNAPSHOT.jar:0.3.1-SNAPSHOT]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [io.cellery.security.cell.sts.server-0.3.1-SNAPSHOT.jar:0.3.1-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: io.cellery.security.cell.sts.server.core.exception.TokenValidationFailureException: No audiences found in the token
	at io.cellery.security.cell.sts.server.core.validators.SelfContainedTokenValidator.validateAudience(SelfContainedTokenValidator.java:98) ~[io.cellery.security.cell.sts.server-0.3.1-SNAPSHOT.jar:0.3.1-SNAPSHOT]
	at io.cellery.security.cell.sts.server.core.validators.SelfContainedTokenValidator.validateToken(SelfContainedTokenValidator.java:66) ~[io.cellery.security.cell.sts.server-0.3.1-SNAPSHOT.jar:0.3.1-SNAPSHOT]
	at io.cellery.security.cell.sts.server.core.service.CelleryCellStsService.validateInboundToken(CelleryCellStsService.java:202) ~[io.cellery.security.cell.sts.server-0.3.1-SNAPSHOT.jar:0.3.1-SNAPSHOT]
	at io.cellery.security.cell.sts.server.core.service.CelleryCellStsService.handleRequestComposite(CelleryCellStsService.java:146) ~[io.cellery.security.cell.sts.server-0.3.1-SNAPSHOT.jar:0.3.1-SNAPSHOT]
	... 12 more

```

**Comment by hasinthaindrajee** [comment]
Fixed with [1]

[1] https://github.com/wso2-cellery/mesh-security/commit/7dab2996304af1fe95ff3616814ae3ce653826eb
