### ISSUE TITLE
Unable to publish APIs with put resources

### ISSUE THREAD

**Issue by anuruddhal** [wso2-cellery/sdk#762]
**Description:**
Deploying a cell file with a Global API that has a PUT resource fails with the following error in the API publisher pod. 
```ballerina
cellery:Component todoServiceComponent = {
        name: "todos",
        source: {
            image: "docker.io/mirage20/samples-todoapp-todos:latest"
        },
        ingresses: {
            todo:  <cellery:HttpApiIngress>{
                   port: 8080,
                   context: "/",
                   definition:{
                       resources: [
                          {
                              path: "/todos",
                              method: "PUT"
                          }                        
                       ]
                   },
                   expose:"global",
                   authenticate:false
               }
        }
};
```

```
[DEBUG] 2019-10-02 09:44:22.555 [main] UpdateManager - Creating Global API payload
[ERROR] 2019-10-02 09:44:22.567 [main] UpdateManager - Error occurred while publishing APIs in Global API manager. Method: PUT is not implemented
io.cellery.cell.api.publisher.exceptions.APIException: Method: PUT is not implemented
	at io.cellery.cell.api.publisher.UpdateManager.getAPIDefinition(UpdateManager.java:503) ~[io.cellery.cell.api.publisher-0.4.1-SNAPSHOT.jar:0.4.1-SNAPSHOT]
	at io.cellery.cell.api.publisher.UpdateManager.createGlobalApiPayload(UpdateManager.java:120) ~[io.cellery.cell.api.publisher-0.4.1-SNAPSHOT.jar:0.4.1-SNAPSHOT]
	at io.cellery.cell.api.publisher.UpdateManager.manageApis(UpdateManager.java:91) ~[io.cellery.cell.api.publisher-0.4.1-SNAPSHOT.jar:0.4.1-SNAPSHOT]
	at io.cellery.cell.api.publisher.UpdateManager.main(UpdateManager.java:67) [io.cellery.cell.api.publisher-0.4.1-SNAPSHOT.jar:0.4.1-SNAPSHOT]
```
This is because we haven't implemented PUT method in https://github.com/wso2-cellery/distribution/blob/master/components/api/io.cellery.cell.api.publisher/src/main/java/io/cellery/cell/api/publisher/UpdateManager.java#L503

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
0.4.0 SNAPSHOT

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madushajg** [comment]
Resolved with [distribution/175](https://github.com/wso2-cellery/distribution/pull/175)
