### ISSUE TITLE
Cellery run fails

### ISSUE THREAD

**Issue by tharindulak** [wso2-cellery/sdk#846]
**Description:**

With the current SDK (0.5.0-SNAPSHOT) 'cellery run' command fails.

cellery run wso2cellery/pet-fe-cell-to-composite:latest -n pet-fe-comp-cell -l petStoreBackend:pet-be-comp -d                                          ✔  10784  14:31:05
✔ Extracting Cell Image wso2cellery/pet-fe-cell-to-composite:latest
✔ Reading Image wso2cellery/pet-fe-cell-to-composite:latest
✔ Parsing dependency links
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Error occurred during initialization of VM
java.lang.Error: Properties init: Could not determine current working directory.
	at java.lang.System.initProperties(Native Method)
	at java.lang.System.initializeSystemClass(System.java:1166)

Failed to start Cell instance pet-fe-comp-cell: failed to execute run method in Cell instance pet-fe-comp-cell due to exit status 1

Failed to start Cell instance pet-fe-composite: failed to execute run method in Cell instance pet-fe-composite due to exit status 1

**Affected Product Version:**
CLI Version:		0.5.0-SNAPSHOT

**OS, DB, other environment details and versions:**    
Mac OS 10.14.6

**Comment by tharindulak** [comment]
This issue was produced when trying to run a cell image in a directory where the particular user does not has permission.
